import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route"
import SessionProvider  from "./components/SessionProvider";

const inter = Noto_Sans({ weight: '400', subsets: ['latin']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}><SessionProvider session={session}>{children}</SessionProvider></body>
    </html>
  );
}
